### PR TITLE
Add phoenix five sub villains

### PR DESCRIPTION
**Pull request by RayosPL**
Moved interfaces fiels to separate folder,
moved randomExtension to common project
Added subvillains for phoenix five with logic to get 2 of them at random
Added flag to not show subvillains if pregames are playing

### CODE REVIEW

**Comment by RayosPL** [comment]
A lot of changes in GameRandomizer.cs due to code cleanup (some methods changed places)

**Comment by norsjensen** [comment]
Sorry, but I do not agree with all of the file moving.

**Comment by RayosPL** [comment]
No worries ;) Do you have some idea how to handle it differently? I assume you will need the randomizer for upcoming season 3, thus moving it to common (and thus, moving interfaces to separate folder), but maybe it can be done in different maner

**Comment by norsjensen** [comment]
I would still make the Engine project handle all randomization, most structures are made with Season 3 in mind.

**Comment by RayosPL** [comment]
I'll try to do it

**Comment by norsjensen** [comment]
Closed as this adds more complexity than the feature is worth.

**Pull request closed without merging**
